version: 3.8"

# docker run --network myNetwork --network-alias mysql -v C:\\Users\\Wazza\\git\\getting-started-app\\todo-mysql-data:/var/lib/mysql 
# -e MYSQL_ROOT_PASSWORD=my-secret-pw -e MYSQL_DATABASE=todos --name mysql -d mysql:8

# docker run --network myNetwork -dp 127.0.0.1:3000:3000 --name todoapp -e MYSQL_HOST=mysql -e MYSQL_USER=root -e MYSQL_PASSWORD=my-secret-pw -e MYSQL_DB=todos getting-started

volumes:
  todo-mysql-data:

services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=todos
    volumes:
      - todo-mysql-data:/var/lib/mysql
    container_name: mysql

  getting-started-app:
    image: tibobzhcesi/getting-started
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DB=todos
    container_name: todoapp
    ports:
      - "3000:3000"
    depends_on:
      - mysql