name: package-getting-started-app
on: [push]
jobs:
  package-getting-started-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: List directory contents and save to file
        run: tree

      - name: Configuration de Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Construction et déploiement
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tibobzhcesi/getting-started:v1
