name: package-getting-started-app
on: [push]
jobs:
  package-getting-started-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: List directory contents and save to file
        run: tree

      - name: Connexion à Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Verification connexion DockerHub
        run: docker run tibocesi/getting-started-app

      - name: Verification connexion DockerHub
        run: docker ps

     
