name: package-getting-started-app
on: [push]
jobs:
  package-getting-started-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: List directory contents and save to file
        run: tree

      - name: Connexion à Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build et Push de l'image Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags:
            TiboCESI/TiboCESI-docker-image:latest
            TiboCESI/TiboCESI-docker-image:${{ github.sha }}
